server:
  port: 8751
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
        min-idle: 0
  # freemarker模板引擎
  freemarker:
    allow-request-override: false
    allow-session-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html;
    expose-request-attributes: true
    expose-session-attributes: true
    template-loader-path: classpath:/templates/
    prefix:
    suffix: .ftl
    request-context-attribute: request
  datasource:
    url: jdbc:mysql://localhost:3306/mr1906?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # model的包
#  type-aliases-package: com.mr.mr_classorder.student.po
  mapper-locations: classpath:/mapper/*.xml
