server:
  port: 8751
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
        min-idle: 0
  # freemarker模板引擎
  freemarker:
    allow-request-override: false
    allow-session-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html;
    expose-request-attributes: true
    expose-session-attributes: true
    template-loader-path: classpath:/templates/
    prefix:
    suffix: .ftl
    request-context-attribute: request
    settings:
      classic_compatible: true
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/mr1906?ullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      initial:size: 15
      max-active: 100
      min-idle: 15


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # model的包
#  type-aliases-package: com.mr.mr_classorder.student.po
  mapper-locations: classpath:/mapper/*.xml
