server:
  port: 8752
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/mr1906?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # model的包
#  type-aliases-package: com.mr.mr_classorder.student.po
  mapper-locations: classpath:/mapper/*.xml
